sudo: required
services:
  - docker

before_install:
  - docker build -t <docker-id>/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true <docker-id>/react-test npm test

after_success:
  - docker build -t <docker-id>/multi-client ./client
  - docker build -t <docker-id>/multi-nginx ./nginx
  - docker build -t <docker-id>/multi-server ./server
  - docker build -t <docker-id>/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push <docker-id>/multi-client
  - docker push <docker-id>/multi-nginx
  - docker push <docker-id>/multi-server
  - docker push <docker-id>/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "<aws-region>"
  app: "<app-name>"
  env: "<environment-name>"
  bucket-name: "<s3-bucket-name>"
  bucker-path: "<app-name>"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
