sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - <encrypted-service-account.json>
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account  --key-file service-account.json
  - gcloud config set project <project-id>
  - gcloud config set compute/zone <region>
  - gcloud container clusters get-credentials <cluster-name>
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t <docker-id>/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true <docker-id>/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
